# Generated by Django 3.2.6 on 2022-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorinfo',
            name='endTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mentorinfo',
            name='startTime',
            field=models.TimeField(default=None, null=True),
        ),
    ]
