# Generated by Django 3.2.6 on 2022-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('forum', '0002_auto_20220206_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(to='user.UserInfo'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='likedBy',
            field=models.ManyToManyField(to='user.UserInfo'),
        ),
    ]
