# Generated by Django 3.2.6 on 2022-02-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20220206_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.ManyToManyField(to='forum.Reply'),
        ),
    ]
