# Generated by Django 3.2.6 on 2022-02-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20220206_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='likedBy',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
